// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARr-XV0Uc7j5foDWAuayjmb9kNcZiHYrc',
    appId: '1:242015412154:web:807cd07e55a02f30bb0783',
    messagingSenderId: '242015412154',
    projectId: 'foodversity-8896b',
    authDomain: 'foodversity-8896b.firebaseapp.com',
    storageBucket: 'foodversity-8896b.appspot.com',
    measurementId: 'G-F4F72GHFN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPTamQLZK7kiQS_U6DK2y1BTtqzbF6E-Y',
    appId: '1:242015412154:android:42e86af26e4f9171bb0783',
    messagingSenderId: '242015412154',
    projectId: 'foodversity-8896b',
    storageBucket: 'foodversity-8896b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz7RlZ15A5m1JfoxTm6VjYNgm_1qBgYG0',
    appId: '1:242015412154:ios:5bb50d600427be38bb0783',
    messagingSenderId: '242015412154',
    projectId: 'foodversity-8896b',
    storageBucket: 'foodversity-8896b.appspot.com',
    iosClientId: '242015412154-2mljjv86ip1pb8sgmuijtutpt32a185u.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodversity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz7RlZ15A5m1JfoxTm6VjYNgm_1qBgYG0',
    appId: '1:242015412154:ios:5bb50d600427be38bb0783',
    messagingSenderId: '242015412154',
    projectId: 'foodversity-8896b',
    storageBucket: 'foodversity-8896b.appspot.com',
    iosClientId: '242015412154-2mljjv86ip1pb8sgmuijtutpt32a185u.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodversity',
  );
}
